cdgriffith/Box

CHANGES.rst, README.rst, box.py, requirements-test.txt, test/test_box.py
Version 2.1.0
=============
* Adding `.update` and `.set_default` functionality
* Adding `dir` support
=> Version 2.1.0

AUTHORS.rst, box.py
Alternate PR as per request made against https://github.com/cdgriffith/Box/pull/29#issuecomment-301824827
=> Pragmatic and future-proof way of keyword lookups

AUTHORS.rst, CHANGES.rst, README.rst, box.py, test/test_functional_box.py
Wow, sorry this took so long to get around to (new job, life, etc...). 
@matan129 and @polishmatt,   Thank you for finding those bugs and code contributions to fix them. I needed to modify how they were handled and this PR happens to (hopefully) handle both those issues. 
If you could both please look at the last file, the tests, and just make sure that your respective bug would be caught with it, would be much appreciated.
=> Issues #46 & #48

AUTHORS.rst, CHANGES.rst, README.rst, box.py, test/test_functional_box.py
Idea from https://github.com/cdgriffith/Box/issues/45
=> Ordered box

.travis.yml, AUTHORS.rst, CHANGES.rst, box.py, test/test_functional_box.py, test/test_unittests_box.py
* Adding hash abilities to new frozen BoxList
* Fixing hashing returned unpredictable values (thanks to cebaa)
* Fixing update to not handle protected words correctly (thanks to deluxghost)
* Removing non-collection support for mapping and callable identification
=> Version 3.2.2

AUTHORS.rst, CHANGES.rst, README.rst, box.py, requirements-test.txt, test/test_functional_box.py
* Adding `BoxObject` (thanks to Brandon Gomes)
=> Version 3.3.0

box.py, test/test_functional_box.py
#78 
```python
from box import Box
class MyList(list): 
def sq(self):
return [x*x for x in self]
b = Box(a = MyList([1,2,4]), box_intact_types = (MyList, ))
b.a.sq()
```
=> Add `box_intact_types`

.coveragerc, CHANGES.rst, README.rst, box.py, test/common.py, test/test_functional_box.py
* Adding `box_intact_types` that allows preservation of selected object types (thanks to pwwang)
* Adding limitations section to readme
=> Version 3.4.0

CHANGES.rst, box.py, requirements-test.txt, test/test_functional_box.py
* Fixing copy of inherited classes (thanks to pwwang)
* Fixing `get` when used with default_box
=> Version 3.4.1

CHANGES.rst, MANIFEST.in, box.py, test/test_functional_box.py
Adding license to source distribution for https://github.com/cdgriffith/Box/issues/92
=> Version 3.4.2

AUTHORS.rst, CHANGES.rst, box.py, test/common.py, test/test_functional_box.py
* Fixing pop not properly resetting box_heritage (thanks to Jeremiah Lowin)
=> Version 3.4.4

AUTHORS.rst, CHANGES.rst, box.py, test/test_functional_box.py
* Fixing #105 update does not convert new sub dictionaries or lists (thanks to Michael Stella)
=> Version 3.4.5

box.py
=> Fix simple typo: specfic -> specific

AUTHORS.rst, CHANGES.rst, box.py, test/test_functional_box.py
* Fixing allowing frozen boxes to be deep copyable (thanks to jandelgado)
=> Version 3.4.6

CHANGES.rst, README.rst, box/__init__.py, setup.py
* Fixing setup.py for release
* Fixing documentation link
=> Version 4.0.1

AUTHORS.rst, CHANGES.rst, box/__init__.py, box/converters.py, setup.py, test/test_box.py
* #119 Fixing converters to properly pass through new box arguments (thanks to Marcelo Huerta)
=> Version 4.0.2

.gitignore, CHANGES.rst, README.rst, box/__init__.py, box/box.py, docs/4.x_changes.rst, test/test_box.py
Version not found
* Fixing `get` to return None when not using default box (thanks to Jeremiah Lowin)
* Updating outdated docs
=> Version 4.0.4

AUTHORS.rst, CHANGES.rst, box/__init__.py, box/box.py, box/box_list.py, box/config_box.py, box/converters.py, box/from_file.py, test/test_box.py
* Adding optimizations for speed ups to creation and inserts
* Adding internal record of safe attributes for faster lookups, increases memory footprint for speed (thanks to Jonas Irgens Kylling)
* Adding all additional methods specific to `Box` as protected keys
* Fixing `merge_update` from incorrectly calling `__setattr__` which was causing a huge slowdown (thanks to Jonas Irgens Kylling)
* Fixing `copy` and `__copy__` not copying box options
=> Version 4.2.0

AUTHORS.rst, CHANGES.rst, README.rst, box/__init__.py, box/box.py
* Fixing README.md example #149 (thanks to J Alan Brogan)
* Changing `protected_keys` to remove magic methods from dict #146 (thanks to Krishna Penukonda)
Fixes #149
Fixes #146
=> Version 4.2.3

.github/workflows/tests.yml, .pre-commit-config.yaml, CHANGES.rst, box/__init__.py, box/box.py, box/box_list.py, box/converters.py, box/from_file.py, setup.py, test/test_box.py, test/test_box_list.py, test/test_config_box.py, test/test_converters.py, test/test_from_file.py, test/test_sbox.py
=> Bugfix dots default

.github/workflows/tests.yml, .pre-commit-config.yaml, CHANGES.rst, box/__init__.py, box/box.py, box/box_list.py, box/converters.py, box/from_file.py, setup.py, test/test_box.py, test/test_box_list.py, test/test_config_box.py, test/test_converters.py, test/test_from_file.py, test/test_sbox.py
* Adding testing for Python 3.9
* Fixing #165 `box_dots` to work with `default_box`
=> Version 5.1.1

AUTHORS.rst, box/box.py, test/test_box.py
=> Make it harder to modify frozen boxes

.github/workflows/tests.yml, box/__init__.py, box/box.py, box/box_list.py, setup.py, test/test_box.py
Removes some issues that I was seeing in the CI output.
I'm ignoring `E203` since it's a stylistic clash between black and flake8.
=> Fix Flake8 issues

CHANGES.rst, box/box.py, test/test_box.py
=> Maintain stacktrace cause for BoxKeyError and BoxValueError

CHANGES.rst, README.rst, box/__init__.py, box/box.py, test/test_box.py
* Fixing #218 Box dots would not raise KeyError on bad key (thanks to Cliff Wells)
* Fixing #217 wording in readme overview needed updated (thanks to Julie Jones)
=> Version 6.0.1

.github/workflows/pythonpublish.yml, CHANGES.rst, box/__init__.py
Fixing Cython optimized build deployments for linux
=> Version 7.1.1

box/box.py
=> Fix type 'int' not iterable

box/converters.py
Version requirement is ruamel >= 0.17
=> Ensure consistent error message about missing YAML parser
