box.py
Module ``ruamel.yaml`` is quite a common alternative to PyYAML, and is a drop-in replacement in nearly every case. See https://yaml.readthedocs.io/en/latest/pyyaml.html for more information.
=> Support for ruamel.yaml

AUTHORS.rst, README.rst, box.py, requirements-test.txt, test/test_functional_box.py
In this feature request, I am proposing a generic extension to the `wrapt.ObjectProxy` which attaches a `Box` as a replacement for the internal `__dict__` for any wrappable object. Features added:
- **_Fully Optional_**: The inclusion of this feature depends on the user's environment. The functionality will only be added if the user has `wrapt` in their Python environment, just like the `yaml` support.
- **_Doesn't Replace `BoxList`_**: Since `BoxList` adds its elements as `Box`es and not as generic objects the elements of `BoxObject([])` are not the same as `BoxList`. Both of these objects serve different goals.
- **_Adds Boxes Everywhere_**: Now that any object can be a `Box`, even a function, properties can be very easily added to anything; Boxes can now be used more uniformly …
=> Feature Request: "BoxObject" — Wrapper for Objects with __dict__ as a Box

box.py, test/test_functional_box.py
=> Add `box_intact_types` (#81)

.gitignore, AUTHORS.rst, CHANGES.rst, box.py, test/test_functional_box.py
* Fixing propagation of box options when adding a new list via setdefault (thanks to Stretch)
* Fixing update does not keep box_intact_types (thanks to pwwang)
* Fixing update to operate the same way as a normal dictionary (thanks to Craig Quiter)
* Fixing deepcopy not copying box options (thanks to Nikolay Stanishev)
=> Version 3.4.3

AUTHORS.rst, box/box.py, box/converters.py, test/test_box.py
=> Solves issue#59 - Treat None values as non-existing keys for default_box

box.py
This is a small tweak, but you can't pass `None` as the default value when calling `get` on a DefaultBox. It interprets `None` as "not specifying a default" instead of "the default value I want" and returns a new DefaultBox. A quick solution is to use a sentinel `object` instead of `None`. 
```
import box
b = box.Box()
b.get('x', None) # None
```
=> Allow .get(default=None) with defaultbox

box.py, test/test_functional_box.py
Currently, deepcopy on a frozen box raises an error:
```python
>>> import copy
>>> from box import Box
>>> b=Box(data={'a':1}, frozen_box=True)
>>> bb=copy.deepcopy(b)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib64/python3.7/copy.py", line 161, in deepcopy
y = copier(memo)
File "/home/jdelgado/src/Box/box.py", line 415, in __deepcopy__
out[copy.deepcopy(k, memodict)] = copy.deepcopy(v, memodict)
File "/usr/lib64/python3.7/copy.py", line 161, in deepcopy
y = copier(memo)
File "/home/jdelgado/src/Box/box.py", line 415, in __deepcopy__
out[copy.deepcopy(k, memodict)] = copy.deepcopy(v, memodict)
File "/home/jdelgado/src/Box/box.py", line 534, in __setitem__
raise BoxError('Box is frozen')
box.BoxError: Box is frozen
```
This PR provides a fix.
=> fix: make frozen box deep copyable

.gitignore, box/box.py, test/test_box.py
In #107 I fixed calling `.get(key, None)` so it worked for DefaultBoxes, but neglected to account for the case where Box is a non-DefaultBox.
In the current release of Box, `Box().get('x')` returns `object()`. This PR fixes it so `Box().get('x')` is `None`, as expected. (and adds tests)
=> Fix issue when calling .get() from non-default box

.coveragerc, .gitignore, AUTHORS.rst, CHANGES.rst, LICENSE, README.rst, box/__init__.py, box/box.py, box/box_list.py, box/config_box.py, box/converters.py, box/exceptions.py, box/from_file.py, box/shorthand_box.py, docs/4.x_changes.rst, docs/source/conf.py, requirements-test.txt, setup.py, test/test_box.py, test/test_box_list.py, test/test_sbox.py
* Adding support for list traversal with `box_dots` (thanks to Lei)
* Adding `BoxWarning` class to allow for the clean suppression of warnings
* Fixing default_box_attr to accept items that evaluate to `None` (thanks to Wenbo Zhao and Yordan Ivanov)
* Changing default_box to set objects in box on lookup
* Fallback to `PyYAML` if `ruamel.yaml` is not detected (thanks to wim glenn)
=> Version 4.1.0

box/box.py
This fixes [#129](https://github.com/cdgriffith/Box/issues/129).
Because of `_conversion_checks` the complexity of a single `__setattr__` is something like O(number_of_keys * key_size). Hence the complexity of merge_update would be O(number_of_keys * number_of_keys * key_size). This comes as a surprise when you expect the complexity to be O(number_of_keys * log(number_of_keys)).
This PR addresses this performance issue by using a dictionary mapping safe keys to old keys.
All the unit tests are passing. I am not familiar enough with Box to know if the use of `__setattr__` and `__setitem__` might lead to an inconsistent state of the Box, or if the unit tests cover this. Eventually, you might consider refactoring the code a bit (this is better done by the author who knows the code well).
=> Speed up crud operations.

box/box.py
removing a missing print call
There was a print outputting keys on [dynaconf](https://github.com/rochacbruno/dynaconf), so it took me some time to understand that this was coming from box.
=> Removing missing print

AUTHORS.rst, CHANGES.rst, README.rst, box/__init__.py, box/box.py
* Fixing uncaught print statement (thanks to Bruno Rocha)
* Fixing old references to `box_it_up` in the documentation
=> Version 4.2.1

AUTHORS.rst, CHANGES.rst, box/__init__.py, box/box.py, test/test_box.py
* Fixing `default_box` doesn't first look for safe attributes before falling back to default (thanks to Pymancer)
=> Fixing #141

AUTHORS.rst, CHANGES.rst, box/box.py, test/test_box.py
when using box.setdefault with dict, it returned a 'detached' object that did not reflect changes on the original box
i.e. if using b = a.setdefault('x', {}), updated to 'b' did not reflect to 'a'
simple fix.
added test.
this is my 1st contribution, so if something is missing, please let me know
=> Issue157 bug in box.setdefault

.github/workflows/tests.yml
The environment variable that needs to set seems to have changed as of [this PR][1]
[1]: https://github.com/coveralls-clients/coveralls-python/pull/227
=> Fix coveralls.

.github/workflows/tests.yml, AUTHORS.rst, CHANGES.rst, box/__init__.py, box/box.py, box/box_list.py, requirements-test.txt, setup.py, test/test_box.py
* Adding checks for frozen boxes to `pop`, `popitem` and `clear` (thanks to Varun Madiath)
* Fixing requirements-test.txt (thanks to Fabian Affolter)
* Fixing Flake8 conflicts with black (thanks to Varun Madiath)
* Fixing coveralls update (thanks to Varun Madiath)
Co-authored-by: Varun Madiath <vamega@gmail.com>
Co-authored-by: Fabian Affolter <mail@fabian-affolter.ch>
=> Version 5.2.0

AUTHORS.rst, CHANGES.rst, box/__init__.py, box/box.py, test/test_box.py
`box_recast` doesn't support non-class callables (functions, methods, etc) because the `issubclass` check fails for non-classes. This adds a guard check to only do the subclass check for classes. This allows one to use a validation or parsing function rather than just instantiating a class.
=> Support box_recast with functions and other non-classes

CHANGES.rst, box/box.py
__recast was being called twice - once in __setattr__ and again in __setitem__. Since __setattr__ defers to __setitem__, we don't need to call in __setattr__. Also, some of the "is frozen" checks weren't aligned between the two methods (so fixed to make them match).
=> Remove duplicate __recast call

.github/workflows/pythonpublish.yml, .github/workflows/tests.yml, AUTHORS.rst, CHANGES.rst, README.rst, box/__init__.py, box/box.py, box/box_list.py, test/test_box.py
* Adding support for functions to box_recast (thanks to Jacob Hayes)
* Adding #181 support for extending or adding new items to list during `merge_update`  (thanks to Marcos Dione)
* Fixing maintain stacktrace cause for BoxKeyError and BoxValueError (thanks to Jacob Hayes)
* Fixing #177 that emtpy yaml files raised errors instead of returning empty objects (thanks to Tim Schwenke)
* Fixing #171 that `popitems` wasn't first checking if box was frozen (thanks to Varun Madiath)
Co-authored-by: Jacob Hayes <jacob.r.hayes@gmail.com>
=> Version 5.3.0

test/test_setdefault.py
Test **setdefault** functionality using a variety of box types:
* vanilla box -- use **setdefault** set set scalar, dict and list values. Validate correct values and types
* dot box -- use dot notation when fetching values
* dot + default box -- use **setdefault** on non-existent items to trigger creation of empty Box dictionaries
=> Numerous setdefault tests

AUTHORS.rst, CHANGES.rst, test/test_box.py, test/test_box_list.py, test/test_converters.py, test/test_from_file.py, test/test_sbox.py
The `toml` package is deprecated and in process of being removed from at least Gentoo and Fedora.  Since the package wishes to preserve support for it, make it possible to run the test suite without it through skipping the relevant tests if `toml` is not available.
=> Support skipping tests requiring the deprecated `toml` package

AUTHORS.rst, box/box.py, test/test_box.py
As requested to issue #211, this PR makes adding property with getter, setter and deleter to Box possible.
The idea is to check if the field is a property (a private function `_get_property_func` was added for this), if so, 
for setter, getter or deleter, box will route to the customized function if exists else the original implementation.
=> Add property support for Box

box/box.py, test/test_box.py
I'd like to track the "namespace" of nested boxes, which is hard to do in a subclass because of the (necessary) recursive conversions during `__init__` and other actions. To handle this, I added a new `box_namespace` parameter, which is tracked in `_box_config`, to allow propagating and extending the namespace as we create nested boxes.
Closes #226
---
This recreates https://github.com/cdgriffith/Box/pull/227 after the `develop` branch was replaced. I updated it to avoid creating an intermediate box config when not needed (as per https://github.com/cdgriffith/Box/pull/227#discussion_r946289689). There were two [open questions](https://github.com/cdgriffith/Box/pull/227#issuecomment-1216089919) on how to label elements of lists and whether to add a `box_history` accessor, but I'd be fine …
=> Add box_namespace to track nested Box names

pyproject.toml
The `tool.poetry.extras` fields takes package names, not full names+versions (the version constraints are pulled from the main dependency spec). Apparently, poetry would silently drop invalid (or maybe just unmatched) extra names, so `ruamel` and `tomli`, which had version constraints in the extras name, were not correctly marked as extra.
Here's some of the generated `METADATA` file before:
```
Requires-Dist: PyYAML (>=6.0) ; extra == "pyyaml"
Requires-Dist: msgpack (>=1.0.0) ; extra == "all" or extra == "msgpack"
Requires-Dist: ruamel.yaml (>=0.17)
Requires-Dist: toml (>=0.10.2) ; extra == "toml"
Requires-Dist: tomli (>=1.2.3) ; python_version < "3.11"
Requires-Dist: tomli-w (>=1.0.0) ; extra == "all" or extra == "tomli"
```
and after:
```
Requires-Dist: PyYAML (>=6.0) ; extra == …
```
=> Fix Poetry extras metadata

pyproject.toml
Fix the `include` entries in `pyproject.toml` to limit documentation files to the sdist format.  Otherwise, they are included top-level in the generated wheels, and end up being installed straight into site-packages, e.g.:
/usr/lib/python3.11/site-packages/LICENSE
/usr/lib/python3.11/site-packages/CHANGES.rst
/usr/lib/python3.11/site-packages/AUTHORS.rst
=> Stop installing docs straight into site-packages

box/box.py
When ipython is installed, `from box import Box` takes 0.5s.
Before this PR:
With this PR:
Using `python -X importtime -c "from box import Box" 2> hs.txt && tuna hs.txt`
=> Defer ipython import

box/box_list.py, test/test_box_list.py
Allow BoxList to use numpy-style tuple indexing, similar to `l[0,1,2,3]`, which is equivalent to `l[0][1][2][3]`.
=> Add support for accessing nested items in BoxList using numpy-style tuple indexing.

box/box_list.py, test/test_box_list.py
I read #251 and think that using `is` operator to identify objects may fix the problem `id` brings.
For now, you can:
1. initialize a `BoxList` with a list with circular references
```py
>>> from box import BoxList
>>> a = []
>>> a.append(a)
>>> a
[[...]]
>>> b = BoxList(a)
>>> b
BoxList([[...]])
>>> b[0][0][0][0] is b
True
```
2. reference oneself after creation
```py
>>> a = BoxList()
>>> a
BoxList([])
>>> a.append(a)
>>> a
BoxList([[...]])
>>> a[0][0][0][0] is a
True
```
Note this:
```py
>>> a = []
>>> b = BoxList(a)
>>> b.append(a)
>>> b
BoxList([[]])
>>> b[0] is a
False
```
This is because:
1. For performance, it is a waste to always hold a reference for the `iterable` passing to `__init__`.
2. After initialization, `a` is not the same as `b` anymore, I think users appending `b` to …
=> Fixing #251 support for circular references in lists

AUTHORS.rst, CHANGES.rst, box/box.py, box/box_list.py, box/config_box.py, box/shorthand_box.py
All Box classes have their class names hardcoded into their respective `__repr__` methods, making it so that when subclassing, `__repr__` calls will output the original class names, which is confusing.
Example:
```python
from box import Box
class MyBox(Box):
pass
class ActuallyMyBox(Box):
def __repr__(self):
return f"{type(self).__name__}({self})"
b1 = MyBox(a=1)
b2 = ActuallyMyBox(b=2)
print(repr(b1))
print(repr(b2))
>>> Box({'a': 1})
>>> ActuallyMyBox({'b': 2})
```
Closes #261
=> Altering __repr__ methods to accurately represent subclass names

.github/workflows/pythonpublish.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, AUTHORS.rst, CHANGES.rst, box/__init__.py, box/box.py, box/box_list.py, box/config_box.py, box/shorthand_box.py, test/test_box_list.py
* Adding #266 support for accessing nested items in BoxList using numpy-style tuple indexing (thanks to Bit0r)
* Adding tests and Cython releases for Python 3.12
* Fixing #251 support for circular references in lists (thanks to Muspi Merol)
* Fixing #261 altering all `__repr__` methods so that subclassing will output the correct class name (thanks to Gabriel Tkacz)
* Fixing #267 Fix type 'int' not iterable (thanks to YISH)
=> Version 7.2.0

AUTHORS.rst, box/box.py, box/box_list.py, test/test_box_list.py
=> Creating BoxLists in DefaultBoxes with dot notation

AUTHORS.rst, CHANGES.rst, box/__init__.py, box/box.py, box/box_list.py, box/converters.py, test/test_box.py, test/test_box_list.py
* Fixing #275 default_box_create_on_get is ignored with from_yaml (thanks to Ward Loos)
* Fixing #285 Infinite Recursion when accessing non existent list index in a DefaultBox with box_dots (thanks to Jesper Schlegel)
=> Version 7.3.1

AUTHORS.rst, CHANGES.rst, box/__init__.py, box/box.py, test/test_box.py
* Fixing #288 default get value error when using box_dots (thanks to Sébastien Weber)
=> Version 7.3.2

MANIFEST.in
The sdist previously contained `test/test*.py` (because `setuptools` does that by default), but not the other files in `test/`.
=> Add more test files to sdist
